use crate::data_model;
use crate::ui;
use crate::ui::layout::info::MessageLevel;
use crate::utils;

pub const HELPER: &[&str] = &[
    "Clear intermediate files", 
    "remove the intermediate build files generated by job preview", 
];

pub fn action(states: &mut ui::states::States, store: &data_model::Store) -> anyhow::Result<()> {
    let proj_sel = store.project_sel.as_ref()
        .ok_or(anyhow::Error::msg("no selected project"))?;
    let proj_dir = &proj_sel.dir;
    states.info_states.message = ("Removing job intermediate files ...".to_string(), MessageLevel::Info);
    utils::docker::clear_build_files(proj_dir)?;
    states.info_states.message = (format!("Preview job done for project {}", proj_dir.to_str().unwrap()), MessageLevel::Info);

    let states_current = &mut states.job_states.detail;
    states_current.tab_action = super::Tab::Files;
    Ok(())
}

