use crate::data_model;
use crate::ui;
use crate::ui::layout::info::MessageLevel;
use crate::utils;

pub const HELPER: &[&str] = &[
    "Clear intermediate files", 
    "remove the intermediate build files generated by job preview", 
];

pub fn action(states: &mut ui::states::States, store: &data_model::Store) -> anyhow::Result<()> {
    let proj_dir = utils::project::dir(store)?;
    let job_settings = data_model::job::Job::get_settings(&proj_dir)?;
    states.info_states.message = ("Removing job intermediate files ...".to_string(), MessageLevel::Info);
    utils::docker::prepare_build_files(&proj_dir, &job_settings)?;
    states.info_states.message = (format!("Preview job done for project {}", proj_dir.to_str().unwrap()), MessageLevel::Info);
    Ok(())
}

