use ratatui::prelude::*;
use ratatui::widgets::*;
use crossterm::event;

use crate::data_model;
use crate::ui;
use crate::utils;

pub const HELPER_CLEAR: &[&str] = &[
    "Clear the job project folder", 
    "remove the intermediate files generated by job preview", 
];

#[derive(Default, PartialEq)]
pub enum Tab {
    #[default]
    Preview,
    Clear,
    Run
}

#[derive(Default)]
pub struct States {
    tab_action: Tab,
}


pub fn render(f: &mut Frame, area: Rect, states: &mut ui::States, store: &data_model::Store) {
    let current_style = states.get_style(ui::Focus::Main);
    let states_current = &mut states.job.detail;

    let action_selected = match states_current.tab_action {
        Tab::Preview => 0,
        Tab::Clear => 1,
        Tab::Run => 2,
    };
    let actions = Tabs::new(["[P]review", "[C]lear", "[R]un"])
        .block(Block::bordered().title(" Actions "))
        .select(action_selected)
        .style(current_style);
    let helper_lines: Vec<Line> = match states_current.tab_action {
        Tab::Preview => preview::HELPER,
        Tab::Clear => HELPER_CLEAR,
        Tab::Run => run::HELPER
    }.iter()
        .map(|&s| Line::from(s))
        .collect();
    let helper = Paragraph::new(helper_lines)
        .style(current_style)
        .block(Block::bordered())
        .alignment(Alignment::Left)
        .wrap(Wrap { trim: true });

    let job_id = 0;
    let job_mgr = store.job_mgr.lock().unwrap();
    // TODO: use job id 0 for testing first
    let mut logs: Vec<Line> = job_mgr.logs.get(&job_id)
        .map(|v| {
            v.iter()
            .map(|s| s.as_str())
            .map(Line::from)
            .collect()
        })
        .unwrap_or_default();
    if let Some(log_tmp) = job_mgr.logs_tmp.get(&job_id) {
        logs.push(Line::from(log_tmp.as_str()));
    }
    let job_logs = Paragraph::new(logs)
        .block(Block::bordered())
        .alignment(Alignment::Left)
        .wrap(Wrap { trim: true });

    let top_mid_bottom = Layout::default()
        .direction(Direction::Vertical)
        .constraints([Constraint::Length(3), Constraint::Max(5), Constraint::Min(1)]) 
        .split(area);
    let (top, mid, bottom) = (top_mid_bottom[0], top_mid_bottom[1], top_mid_bottom[2]);

    f.render_widget(actions, top);
    f.render_widget(helper, mid);
    f.render_widget(job_logs, bottom);
}

fn action_clear(states: &mut ui::States, store: &data_model::Store) -> anyhow::Result<()> {
    let proj_dir = params::proj_dir(store)?;
    states.info.message = "Removing job intermediate files ...".to_string();
    utils::docker::clear_build_files(&proj_dir)?;
    states.info.message = format!("File cleaning done for project {}", proj_dir.to_str().unwrap());
    Ok(())
}

pub fn handle_key(key: &event::KeyEvent, states: &mut ui::States, store: &data_model::Store) {
    use event::KeyCode;

    let states_current = &mut states.job.detail;
    match key.code {
        KeyCode::Char('p') | KeyCode::Char('P') => {
            states_current.tab_action = Tab::Preview;
        }
        KeyCode::Char('c') | KeyCode::Char('C') => {
            states_current.tab_action = Tab::Clear;
        }
        KeyCode::Char('r') | KeyCode::Char('R') => {
            states_current.tab_action = Tab::Run;
        }
        KeyCode::Enter => {
            match match states_current.tab_action {
                Tab::Preview => preview::action(states, store),
                Tab::Clear => action_clear(states, store),
                Tab::Run => run::action(states, store)
            } {
                Ok(_) => (),
                Err(e) => states.info.message = format!("job action error: {e}")
            }
        }
        _ => ()
    }
}

mod params;
mod preview;
mod run;
